name: Build, run and test loadbalanced nginx config

on:
  pull_request:
  push:
    branches:
      - master
      - 'issue*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: install ruby bundler
      run: sudo gem install bundler
    - name: build and run app
      run : docker-compose -f docker-compose-lb.yml up -d
    - name: test the loadbalanced nginx version, both apps
      run : |
        cd ./test/test-chiquito-app
        bundle install --path=vendor && bundle exec cucumber -p local
