name: Example install of Ruby 2.6.5 (cached)

on:
  pull_request:
  push:
    branches:
      - master
      - 'issue*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: build and run app
      run : docker-compose up -d
    - name: test the app
      run : |
        cd ./test/test-chiquito-app
        bundle install --path=vendor && bundle exec cucumber -p local
